using System.Globalization;
using System.Text;
using Microsoft.Extensions.Localization;
using Splitbill.Models;

namespace Splitbill.Services;

/// <summary>Display-only projection used by the long JPEG renderer.</summary>
public sealed record TransactionShareExport(
    string FileName,
    string Language,
    string MerchantName,
    string TransactionNumber,
    string TransactionDateText,
    string? PickupPersonName,
    string ParticipantCountText,
    TransactionSharePaymentSummary PaymentSummary,
    IReadOnlyList<TransactionShareParticipant> Participants,
    TransactionShareReceiptSummary ReceiptSummary)
{
    public TransactionShareLabels Labels { get; init; } = new();
}

public sealed record TransactionShareLabels
{
    public string Collected { get; init; } = "collected";
    public string Outstanding { get; init; } = "outstanding";
    public string MenuSubtotal { get; init; } = "Menu subtotal";
    public string Subtotal { get; init; } = "Subtotal";
    public string Total { get; init; } = "Total";
    public string ReceiptSummary { get; init; } = "Receipt summary";
    public string GrandTotal { get; init; } = "Grand total";
    public string GeneratedBy { get; init; } = "Generated by SplitBill";
}

public sealed record TransactionSharePaymentSummary(
    string PaidCountText,
    string AwaitingCountText,
    string UnpaidCountText,
    string CollectedAmountText,
    string OutstandingAmountText);

public sealed record TransactionShareParticipant(
    string ParticipantKey,
    string DisplayName,
    string PaymentStatusText,
    IReadOnlyList<TransactionShareItem> Items,
    string MenuSubtotalText,
    IReadOnlyList<TransactionShareAdjustment> Adjustments,
    string FinalAmountText);

public sealed record TransactionShareItem(
    string Name,
    string ShareDescription,
    string AmountText,
    string? SharedWithText);

public sealed record TransactionShareAdjustment(
    string Label,
    string? PercentageText,
    string AmountText,
    bool IsSubtract);

public sealed record TransactionShareReceiptSummary(
    string SubtotalText,
    IReadOnlyList<TransactionShareAdjustment> Adjustments,
    string GrandTotalText);

public interface ITransactionShareExportService
{
    TransactionShareExport Build(
        BillTransaction transaction,
        IReadOnlyList<ParticipantBillBreakdown> breakdowns,
        IReadOnlyCollection<long>? participantIds = null);
}

/// <summary>
/// Converts the calculator-owned transaction state into safe, localized display
/// strings. No identifiers, account credentials, file names, or raw money values
/// are sent to the browser.
/// </summary>
public sealed class TransactionShareExportService(IStringLocalizer<SharedResource> localizer) : ITransactionShareExportService
{
    public TransactionShareExport Build(
        BillTransaction transaction,
        IReadOnlyList<ParticipantBillBreakdown> breakdowns,
        IReadOnlyCollection<long>? participantIds = null)
    {
        ArgumentNullException.ThrowIfNull(transaction);
        ArgumentNullException.ThrowIfNull(breakdowns);
        var participants = transaction.Participants
            .Where(x => participantIds is null || participantIds.Contains(x.Id))
            .ToList();
        if (participants.Count == 0) throw new ArgumentException("At least one participant is required.", nameof(participantIds));

        var breakdownById = breakdowns.ToDictionary(x => x.ParticipantId);
        var selected = participants.Where(x => breakdownById.ContainsKey(x.Id)).ToList();
        if (selected.Count != participants.Count) throw new InvalidOperationException("Participant breakdown is incomplete.");

        var keys = selected.Select((_, index) => $"p{index + 1}").ToArray();
        var namesByItem = BuildSharedNames(transaction, selected);
        var exportedParticipants = selected.Select((participant, index) =>
        {
            var breakdown = breakdownById[participant.Id];
            return new TransactionShareParticipant(
                keys[index],
                DisplayName(participant),
                localizer[participant.PaymentStatus.ToString()].Value,
                breakdown.Items.Select(item => new TransactionShareItem(
                    item.Name,
                    ShareDescription(item.QuantityShare),
                    Money(item.ParticipantAmount),
                    namesByItem.GetValueOrDefault((participant.Id, item.ItemId)))).ToList(),
                Money(breakdown.ItemSubtotal),
                breakdown.Adjustments.Select(ToAdjustment).ToList(),
                Money(breakdown.FinalAmount));
        }).ToList();

        var paid = selected.Where(x => x.PaymentStatus == ParticipantPaymentStatus.Paid).ToList();
        var awaiting = selected.Where(x => x.PaymentStatus == ParticipantPaymentStatus.AwaitingConfirmation).ToList();
        var collected = paid.Sum(x => x.Amount);
        var outstanding = selected.Where(x => x.PaymentStatus != ParticipantPaymentStatus.Paid).Sum(x => x.Amount);
        var pickupParticipantId = transaction.PickupAssignment?.SelectedParticipantId;
        var pickupName = pickupParticipantId.HasValue
            ? selected.FirstOrDefault(x => x.Id == pickupParticipantId.Value)?.Name
            : null;

        return new TransactionShareExport(
            FileName(transaction),
            CultureInfo.CurrentUICulture.Name,
            transaction.MerchantName,
            transaction.TransactionNumber,
            transaction.TransactionDate?.ToString("d", CultureInfo.CurrentUICulture) ?? localizer["NoDate"].Value,
            pickupName,
            localizer["ParticipantCount", selected.Count].Value,
            new TransactionSharePaymentSummary(
                localizer["PaidCount", paid.Count].Value,
                localizer["AwaitingCount", awaiting.Count].Value,
                localizer["UnpaidCount", selected.Count - paid.Count - awaiting.Count].Value,
                Money(collected), Money(outstanding)),
            exportedParticipants,
            new TransactionShareReceiptSummary(
                Money(transaction.Subtotal),
                transaction.Charges.OrderBy(x => x.SortOrder).ThenBy(x => x.Id)
                    .Select(charge => ToAdjustment(charge, transaction.Subtotal)).ToList(),
                Money(transaction.GrandTotal)))
        {
            Labels = new TransactionShareLabels
            {
                Collected = localizer["Collected"].Value,
                Outstanding = localizer["Outstanding"].Value,
                MenuSubtotal = localizer["MenuSubtotal"].Value,
                Subtotal = localizer["Subtotal"].Value,
                Total = localizer["Total"].Value,
                ReceiptSummary = localizer["ReceiptSummary"].Value,
                GrandTotal = localizer["GrandTotal"].Value,
                GeneratedBy = localizer["GeneratedBySplitBill"].Value
            }
        };
    }

    private TransactionShareAdjustment ToAdjustment(ParticipantBillAdjustmentLine adjustment)
        => new(
            string.IsNullOrWhiteSpace(adjustment.Label) ? localizer["OtherAdjustment"].Value : adjustment.Label,
            adjustment.ReceiptPercentage.HasValue ? Percentage(adjustment.ReceiptPercentage.Value) : null,
            Money(adjustment.ParticipantAmount),
            adjustment.Operation == ChargeOperation.Subtract);

    private TransactionShareAdjustment ToAdjustment(TransactionCharge charge, decimal subtotal)
        => new(
            string.IsNullOrWhiteSpace(charge.Label) ? localizer["OtherAdjustment"].Value : charge.Label.Trim(),
            ReceiptReviewNormalizer.CalculateEffectivePercentage(charge.Amount, subtotal) is { } rate ? Percentage(rate) : null,
            Money(charge.Amount),
            charge.Operation == ChargeOperation.Subtract);

    private Dictionary<(long ParticipantId, long ItemId), string?> BuildSharedNames(
        BillTransaction transaction,
        IReadOnlyList<TransactionParticipant> selected)
    {
        var result = new Dictionary<(long, long), string?>();
        foreach (var participant in selected)
        foreach (var allocation in participant.ItemAllocations)
        {
            var names = selected.Where(other => other.ItemAllocations.Any(x => x.TransactionItemId == allocation.TransactionItemId))
                .Where(other => other.Id != participant.Id)
                .Select(DisplayName)
                .Distinct(StringComparer.CurrentCultureIgnoreCase)
                .ToList();
            result[(participant.Id, allocation.TransactionItemId)] = names.Count == 0
                ? null
                : localizer["SharedWith", string.Join(", ", names)].Value;
        }
        return result;
    }

    private string Money(decimal amount) => localizer["CurrencyAmount", amount].Value;

    private static string DisplayName(TransactionParticipant participant)
        => string.IsNullOrWhiteSpace(participant.Name) ? "Participant" : participant.Name.Trim();

    private static string ShareDescription(decimal quantity)
        => $"× {quantity.ToString("0.##", CultureInfo.CurrentUICulture)}";

    private static string Percentage(decimal fraction)
        => fraction.ToString("0.##%", CultureInfo.CurrentUICulture);

    private static string FileName(BillTransaction transaction)
    {
        var merchant = new string(transaction.MerchantName.Where(char.IsLetterOrDigit).ToArray());
        if (merchant.Length == 0) merchant = "Bill";
        merchant = merchant.Length > 60 ? merchant[..60] : merchant;
        var date = transaction.TransactionDate?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "undated";
        return $"SplitBill_{merchant}_{date}.jpg";
    }
}
